SCHEMA_COLUMNS = {
    'event_id': 'int',
    'menu_hint': 'string',
    'event_name': 'string',
    'event_dt': 'timestamp',
    'selection_id': 'int',
    'selection_name': 'string',
    'win_lose': 'int',
    'bsp': 'double',
    'ppwap': 'double',
    'morningwap': 'double',
    'ppmax': 'double',
    'ppmin': 'double',
    'ipmax': 'double',
    'ipmin': 'double',
    'morningtradedvol': 'double',
    'pptradedvol': 'double',
    'iptradedvol': 'double',
    'country': 'string',
    'type': 'string',
    'selection_name_cleaned': 'string',
    'event_date': 'string',
}